matrix:
  - name: Markdown
    sources:
      - 'website/docs/**/*.md'
    default_encoding: utf-8
    aspell:
      lang: en
    dictionary:
      wordlists:
      - spelling.dic
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.context_filter:
          context_visible_first: true
          escapes: '\\[\\`~]'
          delimiters:
          # Ignore multiline content between fences (fences can have 3 or more back ticks)
          # ```
          # content
          # ```
          - open: '(?s)^(?P<open> *`{3,})$'
            close: '^(?P=open)$'

