matrix:
  - name: markdown
    sources:
      - website/docs/**/*.md
    aspell:
      lang: en
  dictionary:
    wordlists:
    - spelling.dic
    pipeline:
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
          - code
          - pre
