- name: A11yWatch - The Accessibility Suite

on:
  pull_request:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      uses: A11yWatch/github-action@v1.2.43
      - uses: a11ywatch/github-action@v1.2.43
        with:
          WEBSITE_URL: https://docs.suborbital.dev
          FAIL_ERROR_COUNT: 1
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN }} 
