- name: A11yWatch - The Accessibility Suite
  uses: a11ywatch/github-action@v1.2.44
  with:
    WEBSITE_URL: ${{ secrets.https://docs.suborbital.dev }}
    FAIL_ERROR_COUNT: 1
    A11YWATCH_TOKEN: ${{ secrets.A11YWATCH_TOKEN }} 
