name: spellcheck

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: igsekor/pyspelling-any@v1.0.4
        name: Spellcheck
